truby/category/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', views.CategoryDetail.as_view(), name='category-detail'),
    url(r'^(?P<category>[-a-zA-Z0-9_]+)/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.ProductDetail.as_view(), name='product-detail'),
]

truby/testimonials/urls.py
from django.conf.urls import url

from . import views


urlpatterns = (
    url(r'^$', views.TestimonialList.as_view(), name='testimonial-list'),
    url(r'^create/$', views.TestimonialCreate.as_view(), name='testimonial-create'),
)

truby/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
import django.views.static
from django.views.generic import DetailView
from django.shortcuts import render_to_response
from django.template import RequestContext

from truby.service.models import Service


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^service/(?P<slug>[-a-zA-Z0-9_]+)/$', DetailView.as_view(queryset=Service.objects.filter(published=True)),
        name='service-detail'),
    url(r'^catalog/', include('truby.category.urls')),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
]


def server_error(request):
    return render_to_response('500.html', {}, context_instance=RequestContext(request))


handler500 = server_error

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

    urlpatterns += (
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),

        url(r'^static/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.STATIC_ROOT,
            'show_indexes': True}),
    )

truby/category/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    title = models.CharField('Название', max_length=150)
    slug = models.SlugField(unique=True)
    published = models.BooleanField('Опубликовано', default=True)
    icon = models.ImageField('Иконка', upload_to='category')
    position = models.PositiveIntegerField('Позиция', default=0)
    menu_title = models.CharField('Название в меню', max_length=150, null=True, blank=True)
    page_title = models.CharField('Title', max_length=150, null=True, blank=True)
    page_description = models.TextField('Description', null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['position']

    def __str__(self):
        return self.title

    def get_meta_title(self):
        return self.page_title or self.title

    def get_meta_description(self):
        return self.page_description or ''

    def get_menu_title(self):
        return self.menu_title or self.title

    @models.permalink
    def get_absolute_url(self):
        if self.products.count() == 1:
            return 'product-detail', [], {'slug': self.products.first().slug, 'category': self.slug}

        return 'category-detail', [], {'slug': self.slug}

    def get_products(self):
        return self.products.filter(published=True)


class Product(models.Model):
    title = models.CharField('Название', max_length=150)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, verbose_name="Категория", related_name="products")
    published = models.BooleanField('Опубликовано', default=True)
    image = models.ImageField('Изображение', upload_to='category')
    position = models.PositiveIntegerField('Позиция', default=0)
    content = RichTextUploadingField('Контент')
    description = models.TextField('Описание')
    page_title = models.CharField('Заголовок', max_length=150, null=True, blank=True)
    page_description = models.TextField('Описание заголовка', null=True, blank=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['position']

    def __str__(self):
        return self.title

    def get_page_title(self):
        if self.page_title:
            return self.page_title
        else:
            return self.title

    def get_page_description(self):
        if self.page_description:
            return self.page_description
        else:
            return ""

    @models.permalink
    def get_absolute_url(self):
        return 'product-detail', [], {'slug': self.slug, 'category': self.category.slug}


class Gost(models.Model):
    name = models.CharField('Название', max_length=30)
    doc = models.FileField('Документ', upload_to='gosts')
    category = models.ForeignKey(Category, verbose_name='Категория', related_name='gosts')

    class Meta:
        verbose_name = 'Гост'
        verbose_name_plural = 'Госты'

    def __str__(self):
        return self.name

truby/info/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin


class InfoPluginModel(CMSPlugin):
    info_text = models.TextField(_('Описание'))
    gost = models.CharField(_('ГОСТ'), max_length=255)
    pdf = models.FileField('pdf', upload_to='info', null=True, blank=True)
    doc = models.FileField('doc', upload_to='info', null=True, blank=True)

    def __str__(self):
        return self.gost

truby/service/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField


class Service(models.Model):
    title = models.CharField('Название', max_length=150)
    slug = models.SlugField()
    published = models.BooleanField('Опубликовано', default=True)
    icon = models.ImageField('Иконка', upload_to='service', help_text='120x120 px')
    position = models.PositiveIntegerField('Позиция', default=0)
    text = RichTextUploadingField('Описание улуги')

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'
        ordering = ['position']

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return 'service-detail', [], {'slug': self.slug}

truby/testimonials/models.py
from django.db import models
from django.utils import timezone
from cms.models import CMSPlugin, Page


class Testimonial(models.Model):
    NEW = 0
    APPROVED = 10
    REJECTED = 20
    SPAM = 30
    STATUSES = (
        (NEW, 'Новый'),
        (APPROVED, 'Одобрен'),
        (REJECTED, 'Отклонен'),
        (SPAM, 'Спам'),
    )
    name = models.CharField('Имя', max_length=100)
    photo = models.ImageField('Фото', upload_to='testimonials', null=True, blank=True)
    company = models.CharField('Компания', max_length=100, null=True, blank=True)
    phone_no = models.CharField('Телефон', max_length=15, null=True, blank=True)
    website = models.CharField('Сайт', max_length=50, null=True, blank=True)
    text = models.TextField('Текст')
    email = models.EmailField()
    stars = models.PositiveIntegerField('Оценка', choices=([(i, str(i)) for i in range(1, 6)]))
    created = models.DateTimeField('Создан', default=timezone.now)
    updated = models.DateTimeField('Обновлен', auto_now=True)
    status = models.PositiveIntegerField('Статус', default=0, choices=STATUSES)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
        ordering = ['-created']

    def __str__(self):
        return self.name


class TestimonialModel(CMSPlugin):
    ORDERING = (
        ('-created', 'По дате'),
        ('-stars', 'По оценке'),
    )
    title = models.CharField('Заголоков блока', max_length=100, default='Отзывы наших партнеров')
    count = models.PositiveIntegerField('Кол-во в списке', default=10)
    ordering = models.CharField('Сортировка', max_length=20, choices=ORDERING, default='-created')
    page_link = models.ForeignKey(
        Page,
        verbose_name='Страница с отзывами',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return '%s отзывов %s' % (self.count, self.get_ordering_display().lower())

    def link(self):
        if self.page_link:
            return self.page_link.get_absolute_url()
        return None

truby/category/views.py
from django.views.generic import DetailView

from .models import Product
from .models import Category


class CategoryDetail(DetailView):
    def get_queryset(self):
        return Category.objects.filter(published=True)


class ProductDetail(DetailView):
    def get_queryset(self):
        return Product.objects.filter(published=True, category__slug=self.kwargs['category'])

truby/testimonials/views.py
from django.http import JsonResponse
from django.views.generic import ListView
from django.views.generic import CreateView

from .models import Testimonial


class TestimonialList(ListView):
    def get_queryset(self):
        return Testimonial.objects.filter(status=Testimonial.APPROVED)


class TestimonialCreate(CreateView):
    model = Testimonial
    fields = ('name', 'company', 'email', 'phone_no', 'text')

    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 'ok'})

    def form_invalid(self, form):
        return JsonResponse({'status': 'error', 'errors': form.errors})

truby/templates/base.html
{% load menu_tags static cms_tags sekizai_tags service_tag category_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta name="yandex-verification" content="8afbe83b8aeeeb8e" />
    <meta name="cmsmagazine" content="eb4fcaeada596c995a964eb0097c0aec" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
    <link rel="icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">

    {% block meta %}
        <title>{% page_attribute "page_title" %}</title>
    {% endblock %}

    {% addtoblock "css" %}
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
        <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "js/jquery.fancybox.min.js" %}"></script>
        <script src="{% static "js/lightslider.min.js" %}"></script>
        <script src="{% static "js/main.min.js" %}"></script>
    {% endaddtoblock %}
</head>
<body>
{% cms_toolbar %}
<div class="wrap">
    <div class="container">

        <header class="header">
            <div class="header__phone">
                <a href="tel:+78005508332">8 800-550-83-32</a> <br>
                <small>Звонок по России бесплатный</small>
            </div>
            <div class="header__logo logo">
                <a href="/">Завод современных тепловых сетей</a>
            </div>
            <div class="header__mail">
                {#% static_placeholder "head_email" %#}
                <a href="mailto:ppurf@mail.ru" onclick="yaCounter42613729.reachGoal('email_click')">ppurf@mail.ru</a>
            </div>
        </header>


        <ul class="nav">
            {% show_menu 0 100 100 100 %}
        </ul>

        <div class="category">
            <div class="row">
                {% category_list as category_list %}
                {% for category in category_list %}
                    <div class="col-sm-2 category__item">
                        <a class="category__link" href="{{ category.get_absolute_url }}">
                            <div class="category__img-wrap">
                                <div class="category__img-border"></div>
                                <img class="category__img" src="{{ category.icon.url }}">
                            </div>
                            <span class="category__name">{{ category.get_menu_title }}</span>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {#    <div class="row">#}
            {% block content %}

            {% endblock %}
    {#    </div>#}

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="contacts">
                            <div class="contacts__header">Контактная информация</div>
                            <div class="contacts__item">
                                <span class="contacts__item-name">Телефон</span>
                                <span class="contacts__item-value"><a href="tel:+78005508332">8 800-550-83-32</a></span>
                            </div>
                            <div class="contacts__item">
                                <span class="contacts__item-name">Адрес</span>
                                <span class="contacts__item-value">
                                    <p>г. Киров, ул. Колесникова 10</p>
                                </span>
                            </div>
                        </div>
                        <div class="copyright">
                            <div class="copyright__text">© 2016 <a href="/">Завод современных тепловых сетей</a></div>
                            <a class="copyright__link" href="http://www.webmeg.ru" target="_blank">Создано в «Web
                                MEG»</a>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="row">
                            <div class="col-sm-5 footer-nav"><span class="footer-nav__header">Продукция</span>
                                <ul class="footer-nav__list">
                                    {% category_list as category_list %}
                                    {% for category in category_list %}
                                        <li class="footer-nav__item">
                                            <a class="footer-nav__link" href="{{ category.get_absolute_url }}">
                                                {{ category.title }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col-sm-5 footer-nav"><span class="footer-nav__header">Услуги</span>
                                <ul class="footer-nav__list">
                                    {% service_list as service_list %}
                                    {% for service in service_list %}
                                        <li class="footer-nav__item">
                                            <a class="footer-nav__link"
                                               href="{{ service.get_absolute_url }}">{{ service.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
{% render_block "css" %}
{% render_block "js" %}
{% static_placeholder "metrics" %}
</body>
</html>

truby/templates/calculator-sc.html
{% extends "calculator.html" %}
{% load static %}

{% block calc-form %}
    <form action="">
        <div class="row">
            <div class="col-md-3 col-md-push-1">
                <div class="form-row">
                    <label class="form-label" for="diameter">Диаметр трубы, мм</label>
                    <input class="form-control" id="diameter" type="number" step="0.1" min="0" required="">
                </div>
                <div class="form-row">
                    <label class="form-label" for="thickness">Толщина скорлупы трубы, мм</label>
                    <input class="form-control" id="thickness" type="number" step="0.1" min="0" required="">
                </div>
                <div class="form-row">
                    <label class="form-label" for="length">Общая длина, м</label>
                    <input class="form-control" id="length" type="number" step="0.01" min="0" required="">
                </div>
                <div class="form-row">
                    <button class="form-submit btn btn_blue calc-btn" type="button">Рассчитать</button>
                </div>
            </div>
            <div class="col-md-4 col-md-push-1">
                <div class="ppu-image">
                    <img class="center-block" src="{% static "img/scorlupa.jpg" %}" alt="">
                </div>
                <div class="result-wrap">
                        <p>Объём, м3:</p>
                        <p class="result"></p>
                    </div>
            </div>
        </div>
    </form>
{% endblock %}

truby/templates/calculator.html
{% extends "base.html" %}
{% load static cms_tags %}

{% block content %}
    <h1>{% page_attribute "title" %}</h1>
    <div class="calculator">
        {% block calc-form %}
            <form class="js-calc" action="">
                <div class="row">
                    <div class="col-md-3 col-sm-10">
                        <p class="pipe-type-caption">Тип трубы</p>
                        <ul class="pipe-type">
                            <li class="active">
                                <a data-field-group="circle">Круглая</a>
                            </li>
                            <li>
                                <a data-field-group="rectangle">Прямоугольная</a>
                            </li>
                            <li>
                                <a data-field-group="square">Квадратная</a>
                            </li>
                        </ul>
                        <p class="pipe-descr">Изделие на основе замкнутого полого профиля постоянного сечения</p>
                    </div>
                    <div class="col-md-3 col-sm-5">
                        <form action="" class="js-calc">
                            <div class="form-row calc-field square rectangle hidden">
                                <label class="form-label" for="side-a">Сторона a, мм</label>
                                <input class="form-control" id="side-a" type="number" step="0.1" min="0" required>
                            </div>
                            <div class="form-row calc-field rectangle hidden">
                                <label class="form-label" for="side-b">Сторона b, мм</label>
                                <input class="form-control" id="side-b" type="number" step="0.1" min="0" required>
                            </div>
                            <div class="form-row calc-field circle">
                                <label class="form-label" for="diameter">Диаметр трубы D, мм</label>
                                <input class="form-control" id="diameter" type="number" step="0.1" min="0" required>
                            </div>
                            <div class="form-row calc-field circle square rectangle">
                                <label class="form-label" for="thickness">Толщина стенки s, мм</label>
                                <input class="form-control" id="thickness" type="number" step="0.1" min="0"
                                       required>
                            </div>
                            <div class="form-row">
                                <label class="form-label" for="material">Материал трубы</label>
                                <select class="form-control" name="material" id="material">
                                    <option value="7850">Углеродистая сталь</option>
                                    <option value="7900">17X18H9</option>
                                    <option value="7960">06XH28MДT</option>
                                    <option value="7700">12X17</option>
                                    <option value="7950">12X18H10T</option>
                                    <option value="8100">08X17H15M3T</option>
                                    <option value="7600">15X25T</option>
                                    <option value="8000">10X17H13M2T</option>
                                    <option value="2850">Дюралюминий</option>
                                    <option value="4540">Титан</option>
                                    <option value="8960">Медь</option>
                                    <option value="8600">Латунь</option>
                                    <option value="11340">Свинец</option>
                                    <option value="19300">Золото</option>
                                </select>
                            </div>
                            <div class="form-row">
                                <label class="form-label" for="density">Плотность материала, кг/м3</label>
                                <input class="form-control" id="density" type="text" value="7850" required readonly>
                            </div>
                        </form>
                        <div class="form-row">
                            <button class="form-submit btn btn_blue calc-btn" type="button">Рассчитать</button>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-5">
                        <div class="pipe-image">
                            <img class="calc-field circle" src="{% static "img/pipe.svg" %}" alt="">
                            <img class="calc-field rectangle hidden" src="{% static "img/pipe-b.svg" %}" alt="">
                            <img class="calc-field square hidden" src="{% static "img/pipe-a.svg" %}" alt="">
                        </div>
                        <div class="result-wrap">
                            <p>Масса одного метра трубы, кг:</p>
                            <p class="result"></p>
                        </div>
                    </div>
                </div>
            </form>
        {% endblock %}
    </div>
{% endblock %}

truby/templates/contacts.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags %}

{% addtoblock "js" %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
{% endaddtoblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-5 col-sm-5 map">
            <h2>Карта проезда</h2>
            <div class="map__wrap">
                {% placeholder "map" %}
            </div>
            {% placeholder "content" %}
        </div>
        <div class="col-lg-5 col-sm-5 feedback">
            <h2>Форма обратной связи</h2>
            {% placeholder "feedback-form" %}
        </div>
    </div>
{% endblock %}

truby/templates/delivery.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    <h1>{% page_attribute "title" %}</h1>
    <div class="row">
        <div class="col-sm-5 delivery">
            {% placeholder "content_left" %}
        </div>
        <div class="col-sm-5 delivery">
            {% placeholder "content_right" %}
        </div>
    </div>
{% endblock %}

truby/templates/index.html
{% extends "base.html" %}
{% load static cms_tags sekizai_tags service_tag %}
{% block content %}
    <div class="row">
        <div class="col-md-5 about">
            {% placeholder "content" %}
        </div>
        <div class="col-md-5 service">
            <h2>Услуги</h2>
            <div class="row">
                {% service_list 4 as service_list %}
                {% for service in service_list %}
                    <div class="col-sm-5 service__item">
                        <a href="{{ service.get_absolute_url }}">
                            <div class="service__img-wrap">
                                <img src="{{ service.icon.url }}">
                            </div>
                            <div class="service__name">{{ service.title }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% placeholder "testimonials" %}
{% endblock %}

truby/templates/info.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    <h1>{% page_attribute "title" %}</h1>
    {% placeholder gost %}
{% endblock %}

truby/templates/production.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    <h1>{% page_attribute "title" %}</h1>
    {% placeholder content %}

    <div id="lightslider">
        {% placeholder slider %}
    </div>
{% endblock %}

truby/templates/text.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    <h1>{% page_attribute "title" %}</h1>
    {% placeholder content %}
{% endblock %}